name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: v1.20.x
          cache: true
      - name: Install tinygo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.28.1
      - name: Build binary
        run: make build
      - name: Run e2e tests
        run: make e2e
